# config/packages/messenger.yaml
framework:
  messenger:
    enabled: true
    default_bus: messenger.bus.default
    failure_transport: failed

    transports:
      # Transport sync = exécution immédiate dans la requête HTTP
      sync: 'sync://'

      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          table_name: messenger_messages
        retry_strategy:
          max_retries: 3
          delay: 1000
          multiplier: 2
          max_delay: 0
          jitter: 0.1

      failed:
        dsn: 'doctrine://default?queue_name=failed'
        options:
          table_name: messenger_messages

    buses:
      messenger.bus.default: ~

    routing:
      # ⚠️ FORCER LES EMAILS EN SYNCHRONE
      # Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
      App\Message\Email\SendOrderEmail: async

      # Le reste peut rester async si tu veux
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async
      # App\Message\*: async

    stop_worker_on_signals: []
