vich_uploader:
    db_driver: orm

    mappings:
        category:
            uri_prefix: /uploads/category
            upload_destination: '%kernel.project_dir%/public/uploads/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        subCategory:
            uri_prefix: /uploads/subCategory
            upload_destination: '%kernel.project_dir%/public/uploads/subCategory'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        product:
            uri_prefix: /uploads/product
            upload_destination: '%kernel.project_dir%/public/uploads/product'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        productVariant:
            uri_prefix: /uploads/productVariant
            upload_destination: '%kernel.project_dir%/public/uploads/productVariant'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        email_template_logo:
            uri_prefix: /uploads/emailTemplates
            upload_destination: '%kernel.project_dir%/public/uploads/emailTemplates'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    
  