# config/services.yaml
parameters:
  app.email.from_address: 'no-reply@exemple.com'
  app.email.from_name: 'Votre Boutique'
  app.email.reply_to: 'support@exemple.com'

  app.stripe.webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'


services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  # OrderEmailService : on lui passe les paramètres d'email (+ projectDir)
  App\Service\OrderEmailService:
    arguments:
      $fromEmail: '%app.email.from_address%'
      $fromName: '%app.email.from_name%'
      $replyTo: '%app.email.reply_to%'
      $projectDir: '%kernel.project_dir%'


  #  Stripe client : uniquement la config API key (pas d’autres arguments)
  Stripe\StripeClient:
    arguments:
      - { api_key: '%env(STRIPE_SECRET_KEY)%' }

  #  WebhookController : on lui passe le secret du webhook
  App\Controller\Stripe\WebhookController:
    arguments:
      $webhookSecret: '%app.stripe.webhook_secret%'

  # Tes autres services
  App\Services\AdressManager:
    public: true

  App\Services\UserProfileService:
    public: true
